services:
  nuxt-app:
    image: node:20-alpine
    container_name: nuxt_app_dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev -- --host"
