services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_frankenphp
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000 --workers=16 --watch
    volumes:
      - /c/Docker_Other/Franken:/var/www/html
      - /c/Docker_Other/Franken/Docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8585:8000"
    environment:
      - SERVER_NAME=localhost
      - OCTANE_SERVER=frankenphp
    networks:
      - laravel_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: laravel_franken_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  redis_data:
